# Backend
backend = "glx";
# glx-no-stencil = true;
glx-copy-from-front = false;

# Shadows
shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-exclude = [
    # Exclude Polybar from shadows
    "class_g = 'Polybar'",
    "class_g = 'Rofi'"
    # Prevent shadow on Polybar
    # "_GTK_FRAME_EXTENTS@:c"

];

# Fading
fading = true;
fade-delta = 5;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ ];

# Transparency and Opacity
inactive-opacity = 0.8;
active-opacity = 1.0;
frame-opacity = 0.7;
inactive-dim = 0.2;

# Blur
blur-background = true;
blur-background-frame = true;
blur-method = "dual_kawase";
blur-strength = 4;
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];

# Opacity rules
opacity-rule = [
    "90:class_g = 'Alacritty'",
    # Set Polybar transparency (80% opaque)
    "85:class_g = 'Polybar'",
    "90:class_g = 'Code'",
    "90:class_g = 'firefox'"
];

# Other
vsync = true;
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
