[colors]
background = #282828
background-alt = #1d2021
foreground = #EBDBB2
primary = #D79921
secondary = #458588
alert = #CC241D
disabled = #928374
focused-bkg = #3f3f3f

[global/wm]
margin-bottom = 0
margin-top = 0


[bar/main]
width = 100%
height = 50
background = ${colors.background}
foreground = ${colors.foreground}
font-0 = Hack Nerd Font:size=13;2
font-1 = JetBrainsMono Nerd Font:size=14;2
fixed-center = true  # Ensures modules in center stay centered
padding-right = 1

# Rounded corners
radius = 10.0  
border-size = 10
# Gruvbox yellow border
# border-color = #d79921  

# Modules
modules-left = bspwm
# modules-center = date
modules-right = date media cpu ram wifi volume mic brightness battery tray


[module/bspwm]
type = internal/bspwm
format = <label-state> <label-mode>

; Label colors
label-focused = %name%
label-focused-background = ${colors.focused-bkg}
label-focused-padding = 2

label-occupied = %name%
label-occupied-padding = 2

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 2

[module/tray]
type = internal/tray
tray-font = 0
format-margin = 8px
tray-spacing = 8px

[module/volume]
type = custom/script
exec = ~/.config/polybar/volume.sh
tail = true
click-left = pamixer -t
click-right = pavucontrol &
scroll-up = pamixer -i 5 --allow-boost --set-limit 150 && ~/.config/polybar/volume.sh
scroll-down = pamixer -d 5 && ~/.config/polybar/volume.sh

[module/mic]
type = custom/script
exec = ~/.config/polybar/mic.sh
interval = 1
click-left = pamixer --default-source -t
click-right = pavucontrol --tab=4

[module/brightness]
type = custom/script
exec = ~/.config/polybar/brightness.sh
tail = true
interval = 1
format = <label>
label =  %output%

[module/wifi]
type = custom/script
# exec = echo "$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2 || echo 'Disconnected')"
exec = ~/.config/polybar/wifi-status.sh
interval = 5
# Open nmtui in terminal
click-left = kitty -e nmtui  
# click-left = ~/.config/rofi/rofi-wifi-menu.sh
# click-right = ~/.config/rofi/rofi-wifi-menu.sh --toggle

[module/media]
type = custom/script
exec = ~/.config/polybar/media-player.sh
tail = true
interval = 1
click-left = playerctl play-pause
click-middle = playerctl stop
click-right = playerctl next
scroll-up = playerctl volume 0.1+
scroll-down = playerctl volume 0.1-
label-maxlen = 30 # Second line of defense

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC0
full-at = 85
low-at = 45
poll-interval = 5

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = Battery:<ramp-capacity> <label-full>

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

ramp-capacity-foreground = #3C5A4C

animation-charging-0 = ⚡
label-discharging =󰁾 Battery: %percentage%%
label-full = 󰁹 | 
label-low = 󰂃

animation-charging-foreground = #36F59C
# Disable animation
animation-charging-framerate = 0

# Time & Date Module
[module/date]
type = internal/date
interval = 1
date = %A | %d-%m-%Y%
time = %H:%M:%S
label = "  %date% %time% | "
click-left = ~/.config/polybar/launch-calcurse.sh

# CPU Module
[module/cpu]
type = internal/cpu
interval = 2
# format-prefix = "CPU: "
label = %percentage%%
format = "|   CPU: <label> | "

# RAM Module
[module/ram]
type = internal/memory
interval = 2
# format-prefix = "RAM: "
label = %percentage_used%%
format = "  RAM: <label> | "


# Memory (Disk Usage)
[module/memory]
type = internal/fs
mount-0 = /
label-mounted = "Disk: %free%/%total% | "

# Network Module
[module/network]
type = internal/network
interface = wlp2s0
interval = 3
# format-connected = "Net: {downspeed} ↓ {upspeed} ↑"
format-connected = "Net: Connected  "
format-disconnected = "Net: Disconnected  "
